### ISSUE TITLE
Stuck in ERROR state when negotiating poll modes

### ISSUE THREAD

**Issue by fredldotme** [mer-hybris/libncicore#21]
Starting up a nfcd session without reverting this commit lands us in the `ERROR` state: https://github.com/mer-hybris/libncicore/commit/f50533301f641fb715c5bd48f27d1ff8a3e909ff

Specifically, the output looks like this: https://paste.ubuntu.com/p/nXggHnmHwR/

This happens on Ubuntu Touch on the Volla Phone and Pixel 3a (arm64 builds).

**Comment by monich** [comment]
Looks like one (or some) of the discovery modes makes NFC chip unhappy (which chip is it, btw?)

Can you figure out which exactly mode is unsupported? They are configured [here](https://github.com/mer-hybris/libncicore/blob/7569d70/src/nci_transition_idle_to_discovery.c#L148).

**Comment by monich** [comment]
And unfortunately NCI 1.0 spec doesn't say how to react to RF_DISCOVER_RSP with STATUS_REJECTED. Your chip seems to be talking NCI 2.x though.

**Comment by fredldotme** [comment]
The Volla Phone uses the st21nfc chip.

What's odd is that libncicore in SailfishOS itself has no similar problems.

Btw, we're hitting another bug right now, causing tags to be removed right after they are detected (https://paste.ubuntu.com/p/rhK4FWJD7S/). Which repo seems more likely to have a new report on that?

**Comment by fredldotme** [comment]
op_modes is decimal 11

**Comment by monich** [comment]
As for RF interface/protocol 0x90, it's not something that we support. It's a value from the range reserved for proprietary use. I have no idea what that is.

Regarding st21nfc, I suspect that this chip just doesn't support some NFC modes, e.g. Type F. Ideally, it should be possible to detect that at NCI level, e.g. by querying some Poll F and/or Listen F configuration parameters during initialization, and if the query fails, assume that Type F technology is unsupported (assuming that the chip chokes on Type F modes, which I'm not sure). That kind of capability detection only needs to be done once in nfcd lifetime, so it won't slow anything down. I can't do much about it though, until I have a device with such a chip in my hands. Which I don't have at the moment :|

**Comment by monich** [comment]
I've got a device which has a similar problem, stay tuned!

**Comment by monich** [comment]
If you have a chance, please check if https://github.com/mer-hybris/libncicore/pull/22 fixes the Type F issue for you. I've been testing it against a different chip, there's no guarantee that it works for yours.

**Comment by fredldotme** [comment]
Yeah I'll let you know when I have time, thanks for the hint!

**Comment by monich** [comment]
meh, it's not going to work, unfortunately. That bit (b1 of LF_PROTOCOL_TYPE) appears to be writeable, and doesn't reflect the actual capability of the chip. I need to come up with something smarter than that (or resort to a config file).

**Comment by monich** [comment]
https://github.com/mer-hybris/libncicore/pull/23 is my next take on it.

**Comment by monich** [comment]
Done, I guess.
