### ISSUE TITLE
P2P not working on ST NFC chips

### ISSUE THREAD

**Issue by fredldotme** [mer-hybris/libncicore#25]
We are in the process of merging nfcd P2P mode into Ubuntu Touch and during testing it
turns out that not all our test devices were able to establish a connection.

The Volla Phone/GS290 and the Pixel 3a use NFC chips made by ST. The Pixel 3a is untested as of yet,
but on the GS290 it didn't detect the Android device ready for Android Beam.
Instead of activation parameters we see "RF Tech Parameters" in the output.

Here is some log output of nfcd during attempting to establish a P2P connection:
https://paste.myself5.de/vegazoguli.rb

The nfcdep-service is started at: `2021-01-19 21:18:09 [nfc-core] NFC mode 0x07`

**Comment by monich** [comment]
Please capture a similar log with `nfcd -vv` to hexdump raw NCI packets too. I wonder what's in RF_INTF_ACTIVATED_NTF that we fail to parse. The protocol field in RF_INTF_ACTIVATED_NTF is 0x05 which is NFC-DEP, LLCP Magic 46h 66h 6Dh is there, it all looks pretty promising actually.

**Comment by fredldotme** [comment]
Thanks for looking into this issue! Here's the requested log output: https://paste.myself5.de/asusoduran.pl

**Comment by monich** [comment]
From a quick glance, we are doing a wrong thing passing both `NFC_A_ACTIVE_LISTEN_MODE` and `NFC_A_PASSIVE_LISTEN_MODE` to `RF_DISCOVER_CMD`. NCI 1.0 spec says:

> To enable Listen Mode for NFC-DEP, the DH sends the RF_DISCOVER_CMD to the NFCC
containing configurations with RF Technology and Mode values of
NFC_A_PASSIVE_LISTEN_MODE and/or NFC_F_PASSIVE_LISTEN_MODE.

Here we are getting `RF_INTF_ACTIVATED_NTF` with `NFC_A_ACTIVE_LISTEN_MODE` activation mode and we are not prepared for that. I'll submit a patch when I have time (hopefully soon).

**Comment by monich** [comment]
And this is what it says about the poll mode:

> To enable Poll Mode for NFC-DEP, the DH sends the RF_DISCOVER_CMD to the NFCC containing configurations with RF Technology and Mode values of NFC_A_PASSIVE_POLL_MODE and/or NFC_F_PASSIVE_POLL_MODE.

**Comment by monich** [comment]
Please try https://github.com/mer-hybris/libncicore/pull/26 and let me know if it helps!

**Comment by fredldotme** [comment]
With #26 it's gotten a little better, but detection still fails.

**Comment by monich** [comment]
Hmm, we are successfully parsing LLCP parameters and expecting a SYMM from the other side but not getting it. My guess is that `LN_ATR_RES_CONFIG`  and `LN_ATR_RES_GEN_BYTES` (`PN_ATR_REQ_CONFIG` and `PN_ATR_REQ_GEN_BYTES` for poll-side) need to be configured for LLCP initialization to succeed. Apparently NXP chips provide reasonable defaults for those and this chip doesn't (and, according to the spec, doesn't have to).

I'll give it a try when I have time, hopefully soon.

**Comment by monich** [comment]
Updated #26 (added explicit configuration of the above mentioned ATR_RES and ATR_REQ parameters), does it help?

**Comment by fredldotme** [comment]
Heck yes, that did it! Thanks for looking into it! :)

**Comment by monich** [comment]
Wow! I'll merge that soon, then.

**Comment by monich** [comment]
Finally merged https://github.com/mer-hybris/libncicore/pull/26, can this issue be closed?
